name: docker release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the release, e.g. v1.0.0"
        default: "v0.1.0"
        required: true

jobs:
  
  git-release:
    permissions:
      contents:
        write
    
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4.1.7
        with:
          persist-credentials: true
          repository: ${{ github.event.pull_request.head.repo.full_name }} # required for commit
          ref: ${{ github.event.pull_request.head.ref }} # required for commit          

      - name: Modify action.yml
        uses: mingjun97/file-regex-replace@7d8ae0144cd6660fe8ca5a938ae71ea816a06f47
        with:
          regex: "image:\\s?'([^']+)'"
          replacement: "image: 'docker://ghcr.io/GITOWNER/ACTIONNAME:${{inputs.version}}'"
          include: 'action.yml$'

      - name: Commit action.yml
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 #v9.1.4
        with:
          default_author: github_actions
          push: false
          add: ./action.yml
          message: 'Version bump'

      - name: tag + push
        run: |
          git tag -f -a ${{ inputs.version }} -m "Release ${{ inputs.version }}"
          git push -f origin ${{ inputs.version }}

      - name: Create Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          tag_name: refs/tags/${{ inputs.version }}
          name: Release ${{ inputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true

  deploy:
    permissions:
      packages: write
      id-token: write
      contents: read
    needs: [git-release]
    uses: taori/actions/.github/workflows/github-dotnet-action-deploy.yml@v11
    with:
      checkoutRef: "refs/tags/${{ inputs.version }}"
      imageName: 'ACTIONNAME'
      push: true
      imageTags: |
        ghcr.io/GITOWNER/ACTIONNAME:${{ inputs.version }}

  verify:
    needs: [deploy]
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: call github action
        id: hw
        uses: GITOWNER/ACTIONNAME@v0.1.0
        with:
          workspace: ${{ github.workspace }}

      - name: output action result
        shell: pwsh
        run: |
          Write-Host "Previous result is ${{ steps.hw.outputs.message }}"