name: .NET

on:
  push:
    branches: [ master ]
    paths: 
      - src/*
      - tests/*
      
  pull_request:
    branches: [ master ]
    types: 
      - opened
      - reopened
      - synchronize 
      - closed
      
  workflow_dispatch:
  
    inputs:   
    
      versionSuffix:
        required: true
        description: "Version suffix for nupkg"
        default: 'beta'
        
      nugetRelease:
        required: true
        description: "nuget release? (1/0)"
        default: '0'

jobs:
  ciTest: 
    runs-on: ubuntu-latest

    steps:
     - name: States
       if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
       shell: pwsh
       run: Write-Host "event_name=${{github.event_name}} eventaction=${{github.event.action}} merged=${{github.event.pull_request.merged}} "
       
     - name: pull merge request
       if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
       shell: pwsh
       run: Write-Host "Merge pull request"
  build:
    if: false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore src/All.sln
    - name: Build
      run: dotnet build src/All.sln --no-restore --verbosity m -c Release
    - name: Test
      run: dotnet test src/All.sln --no-build --verbosity normal -c Release
    - name: Pack
      run: dotnet pack src/Amusoft.Templates/Amusoft.Templates.csproj -o artifacts/nupkg --no-build --verbosity normal -c Release /p:VersionSuffix=${{ github.event.inputs.versionSuffix }}
    
    - name: Release
      run: dotnet nuget push "artifacts/nupkg/*.nupkg" -k $NUGETKEY -s https://api.nuget.org/v3/index.json
      if: ${{ github.event.inputs.nugetRelease == '1' }}
      env:
        NUGETKEY: ${{ secrets.NUGET }}
        
        
    
