name: .NET

on:
  push:
    branches: [ master ]
    paths: 
      - .github/workflows/*
      - src/**/*
      - tests/**/*
      
  pull_request:
    branches: [ master ]
    types: 
      - opened
      - reopened
      - synchronize 
      - closed
      
  workflow_dispatch:
  
    inputs:   
    
      versionSuffix:
        required: false
        description: "Version suffix for nupkg"
        
      nugetRelease:
        required: true
        type: boolean
        description: "Nuget release?"
        default: false

jobs:
  environment : 
    runs-on: ubuntu-latest
    
    outputs:      
      versionSuffix : ${{ steps.defaults.outputs.versionSuffix }}
      verbosity : ${{ steps.defaults.outputs.verbosity }}
      configuration : ${{ steps.defaults.outputs.configuration }}
      publishRelease : ${{ steps.defaults.outputs.publishRelease }}

    steps:
    
      - name: Git Information
        shell: bash
        run: |
          echo "head: $GITHUB_HEAD_REF"
          echo "base: $GITHUB_BASE_REF"
          echo "base: $GITHUB_REF"
          
      - name: declare default values 
        id: defaults
        shell: pwsh
        run: |        
          $automaticTrigger = "$env:GITHUB_EVENT_NAME" -ne "workflow_dispatch"          
          $mergePR = "master|pull_request|closed|true" -eq "${{github.base_ref}}|${{github.event_name}}|${{github.event.action}}|${{github.event.pull_request.merged}}"
          $publishRelease = ("${{ github.event.inputs.nugetRelease }}" -eq "1") -Or ($automaticTrigger -And $mergePR)
          Write-Host "publishRelease: $publishRelease, mergePR: $mergePR, automaticTrigger: $automaticTrigger"
          
          $versionSuffix = "";
          
          if($automaticTrigger) {
            if("${{github.base_ref}}" -eq "master") {
              $versionSuffix = "beta${{github.run_number}}"
            } else {
              $versionSuffix = "alpha${{github.run_number}}"
            }
          } else {
            if([string]::IsNullOrEmpty("${{ github.event.inputs.versionSuffix }}") -eq $true){
              $versionSuffix = ""
            } else {
              $versionSuffix = "${{ github.event.inputs.versionSuffix }}${{github.run_number}}"
            }
          }
          
          $values = @(
              @("versionSuffix", $true, "$versionSuffix", "$versionSuffix"),
              @("publishRelease", $true, "$publishRelease", "$publishRelease"),
              @("verbosity", $true, "${{ github.event.inputs.verbosity }}", "minimal"),
              @("configuration", $true, "${{ github.event.inputs.configuration }}", "Release")
            )
            
          foreach($pair in $values){
            $value = $pair[2]
            if($pair[1] -eq $true -And [string]::IsNullOrEmpty("$value") -eq $true){
                    $value = $pair[3]
            }
            
            Write-Host "Assigning $($pair[0]) => $value"

            echo "::set-output name=$($pair[0])::$value"
          }
          
  build:
    if: true
    runs-on: ubuntu-latest
    needs: environment

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore src/All.sln
    - name: Build
      run: dotnet build src/All.sln --no-restore --verbosity m -c Release
    - name: Test
      run: dotnet test src/All.sln --no-build --verbosity normal -c Release
    - name: Pack
      run: dotnet pack src/Amusoft.Templates/Amusoft.Templates.csproj -o artifacts/nupkg --no-build --verbosity normal -c Release /p:VersionSuffix=${{ needs.environment.outputs.versionSuffix}}
    
    - name: Release
      run: dotnet nuget push "artifacts/nupkg/*.nupkg" -k $NUGETKEY -s https://api.nuget.org/v3/index.json
      if: ${{ needs.environment.outputs.publishRelease == 'True' }}
      env:
        NUGETKEY: ${{ secrets.NUGET }}
        
        
    
