name: .NET

on:
  push:
    branches: [ master ]
    paths: 
      - src/*
      - tests/*
      
  pull_request:
    branches: [ master ]
    types: 
      - opened
      - reopened
      - synchronize 
      
  workflow_dispatch:
  
    inputs:   
    
      versionSuffix:
        required: true
        description: "Version suffix for nupkg"
        default: 'beta'
        
      nugetRelease:
        required: true
        description: "whether or not to publish a nuget release"
        default: '1'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore src/All.sln
    - name: Build
      run: dotnet build src/All.sln --no-restore --verbosity m -c Release
    - name: Test
      run: dotnet test src/All.sln --no-build --verbosity normal -c Release
    - name: Pack
      run: dotnet pack src/Amusoft.Templates/Amusoft.Templates.csproj -o artifacts/nupkg --no-build --verbosity normal -c Release /p:VersionSuffix=${{ github.event.inputs.versionSuffix }}
    
    - name: Release
      run: dotnet nuget push foo.nupkg -k $NUGETKEY -s https://api.nuget.org/v3/index.json
      if: ${{ github.event.inputs.nugetRelease == '1' }}
      env:
        NUGETKEY: ${{ secrets.NUGET }}
    
